framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        #prefix_seed: your_vendor_name/app_name

        app: cache.adapter.redis
        default_redis_provider: redis://redis:6379

        # Namespaced pools use the above "app" backend by default
        #pools:
            #my.dedicated.cache: null
