fos_elastica:
  clients:
    default: { host: elastic, port: 9200 }
  indexes:
    user:
      types:
        user:
          properties:
            id: {type: integer}
            username: {type: text}
            roles: {type: text}
          persistence:
            # the driver can be orm, mongodb or phpcr
            driver: orm
            model: App\Entity\User\User
            provider: ~
            finder: ~
