version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "54320:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
  php:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - './:/usr/src/app'
    user: ${LOCAL_USER}
    links:
      - db
      - redis
  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - './public:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '${NGINX_PORT}:80'
    depends_on:
      - php
  redis:
    image: redis:latest
volumes:
  my_dbdata: